openapi: "3.0.2"
info:
  title: Bot API
  description: API
  contact:
    name: Source
    url: https://github.com/kennib/necsus
  version: 1.0

servers:
  - url: '{url}'
    description: Url to your bot
    variables:
      url:
        description: Full url to your bot.
        default: http://localhost:5000

paths:
  /{path}:
    post:
      description: Endpoint that receives new messages from the chat.
      responses:
        '200':
          description: 'A message to send to the chat room in reply'
          content:
            application/json:
              schema:
                type: object
                required:
                  - text
                  - author # this should not be required
                properties:
                  room:
                    type: string
                  author:
                    type: string # XXX: bot shouldn't be able to set author
                  text:
                    type: string

      requestBody:
        description: A message from the server.
        required: true
        content:
          'application/json':
            schema:
              type: object
              required:
                - room
                - author
                - text
                - params
              properties:
                room:
                  type: string
                author:
                  type: string # TODO: or null
                text:
                  type: string
                params:
                  type: object
                  properties:
                    TODO: # it's a groupdict from the responds-to re
                      type: string

    parameters:
    - name: path
      in: path
      description: Path to the registered endpoint
      required: false
      schema:
        type: string
